### ISSUE TITLE
Newly added contact does not show up unless I refresh browser

### ISSUE THREAD

**Issue by do-n-khanh** [gae-init/phonebook#3]
Hi,

I am at "Changing the redirect" part of step 6 of http://docs.gae-init.appspot.com/tutorial/#create

When I create new contact, it redirects me to http://localhost:8912/contact/?order=-created
But I do not see newly created contact there.
I have to refresh browser to see it.
How do I solve this problem?
Thank you very much.

**Comment by lipis** [comment]
This is due to eventual consistency.. read more about it here: https://cloud.google.com/datastore/docs/articles/balancing-strong-and-eventual-consistency-with-google-cloud-datastore/

When deployed is not that noticeable.
